Repository mailbadger/app, pull requests merged in 2020-09, with the labels that each got.

#738 fix index name for 'clicks' table
  .gitignore
  .idea/app.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  go.mod
  go.sum
  storage/migrations/mysql/1_init.sql
Labels: duplicate

#739 implemented campaign-opens-endpoint Issue#720
  .gitignore
  actions/campaigns.go
  entities/open.go
  routes/routes.go
  storage/campaign.go
  storage/campaign_test.go
  storage/migrations/sqlite3/1_init.sql
  storage/storage.go
Labels: go

#759 Campaing stats endpoint
  .idea/workspace.xml
  actions/campaigns.go
  entities/campaign.go
  go.mod
  go.sum
  routes/routes.go
  storage/bounces_test.go
  storage/campaign.go
  storage/campaign_test.go
  storage/clicks_test.go
  storage/complaints_test.go
  storage/deliveries_test.go
  storage/migrations/sqlite3/1_init.sql
  storage/opens_test.go
  storage/sends_test.go
  storage/storage.go
Labels: go

#760 Campaign stats clicks endpoint
  .idea/app.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  actions/campaigns.go
  entities/campaign.go
  entities/click.go
  routes/routes.go
  storage/campaign.go
  storage/clicks.go
  storage/clicks_test.go
  storage/migrations/sqlite3/1_init.sql
  storage/storage.go
Labels: dependencies, go

#774 Users handler group validation
  actions/users.go
  go.mod
  go.sum
Labels: dependencies, go

#785 Proposal for endpoint validation on PostSESKeys
  actions/responses.go
  actions/ses.go
  entities/params/postseskeys.go
  entities/params/requestbody.go
  validator/fielderror.go
  validator/validationerror.go
  validator/validator.go
Labels: dependencies, go
