Repository mailbadger/app, pull requests merged in 2021-01, with the labels that each got.

#934 Get template
  actions/templates.go
  go.sum
  routes/routes.go
  services/templates/service.go
  storage/db.go
  storage/storage.go
  storage/templates.go
  storage/templates_test.go
Labels: enhancement, go

#980 refactor: templates ui changes - using the newly refactored endpoints
  dashboard/.eslintcache
  dashboard/src/Templates/Create.js
  dashboard/src/Templates/Edit.js
  dashboard/src/Templates/List.js
  dashboard/src/Templates/index.js
  dashboard/yarn.lock
Labels: javascript, ui

#1005 Campaigner consumer reworked
  consumers/bulksender/main.go
  consumers/campaigner/main.go
  entities/campaign.go
  entities/sendbulklog.go
  entities/sendlog.go
  go.mod
  go.sum
  services/campaigns/campaigns.go
  storage/logs.go
  storage/migrations/mysql/1_init.sql
  storage/migrations/sqlite3/1_init.sql
  storage/sendlog.go
  storage/sendlog_test.go
  storage/storage.go
Labels: go
